# Generated by Django 2.2.1 on 2019-06-02 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TAccount',
            fields=[
                ('acc_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TDepartment',
            fields=[
                ('dcode', models.IntegerField(primary_key=True, serialize=False)),
                ('dname', models.CharField(max_length=20)),
                ('minimum_wage', models.DecimalField(decimal_places=3, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='TStaff',
            fields=[
                ('scode', models.IntegerField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=20)),
                ('spassword', models.CharField(max_length=20)),
                ('sgender', models.CharField(max_length=2)),
                ('dcode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wms.TDepartment')),
            ],
        ),
        migrations.CreateModel(
            name='TWage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wyear', models.IntegerField()),
                ('wmonth', models.IntegerField()),
                ('basic_wage', models.DecimalField(decimal_places=3, max_digits=12)),
                ('bonus', models.DecimalField(decimal_places=3, max_digits=12)),
                ('due_wage', models.DecimalField(decimal_places=3, max_digits=12)),
                ('withhold', models.DecimalField(decimal_places=3, max_digits=12)),
                ('final_wage', models.DecimalField(decimal_places=3, max_digits=12)),
                ('scode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms.TStaff')),
            ],
            options={
                'unique_together': {('scode', 'wyear', 'wmonth')},
            },
        ),
        migrations.CreateModel(
            name='TBonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('byear', models.IntegerField()),
                ('bmonth', models.IntegerField()),
                ('full_work_bonus', models.DecimalField(decimal_places=3, max_digits=12)),
                ('overtime_bonus', models.DecimalField(decimal_places=3, max_digits=12)),
                ('yearend_bonus', models.DecimalField(decimal_places=3, max_digits=12)),
                ('scode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms.TStaff')),
            ],
            options={
                'unique_together': {('scode', 'byear', 'bmonth')},
            },
        ),
        migrations.CreateModel(
            name='TAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ayear', models.IntegerField()),
                ('amonth', models.IntegerField()),
                ('scode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms.TStaff')),
            ],
            options={
                'unique_together': {('scode', 'ayear', 'amonth')},
            },
        ),
    ]
