# Generated by Django 2.2.1 on 2019-06-02 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taccount',
            name='isAdmin',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tattendance',
            name='absent_num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tattendance',
            name='overtime_num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tdepartment',
            name='dnumber',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tstaff',
            name='sage',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
