# Generated by Django 2.2.1 on 2019-06-02 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0002_auto_20190602_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taccount',
            name='isAdmin',
        ),
    ]
