# Generated by Django 2.2.1 on 2019-06-05 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0003_remove_taccount_isadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tstaff',
            name='spassword',
        ),
    ]
