# Generated by Django 2.2.1 on 2019-06-06 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0004_remove_tstaff_spassword'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TBonus',
        ),
    ]
