# Generated by Django 2.2.1 on 2019-06-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0005_delete_tbonus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taccount',
            name='acc_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tdepartment',
            name='dcode',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tstaff',
            name='scode',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
