# Generated by Django 2.2.1 on 2019-06-11 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0006_auto_20190606_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='TYearending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('total_amount', models.DecimalField(decimal_places=3, max_digits=12)),
                ('year_bonus', models.DecimalField(decimal_places=3, max_digits=12)),
                ('scode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms.TStaff')),
            ],
            options={
                'unique_together': {('scode', 'year')},
            },
        ),
    ]
